version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/Database1
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: 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
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: Database1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  redis:
    image: redis:6-alpine
    # ports:
    #   - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/Database1
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-super-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      OPENAI_API_KEY: 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
    depends_on:
      - db
      - redis

  chatbot:
    build: ./chatbot
    command: python main.py
    environment:
      OPENAI_API_KEY: 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
      FASTAPI_BASE_URL: http://web:8000/api/v1
      CHATBOT_USERNAME: chatbot_user
      CHATBOT_PASSWORD: chatbot_password
    depends_on:
      - web

volumes:
  postgres_data: 