services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: back
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  redis:
    image: redis:6-alpine
    # ports:
    #   - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: 
  