version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/Database1
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: Database1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  redis:
    image: redis:6-alpine
    # ports:
    #   - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/Database1
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-super-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - db
      - redis

volumes:
  postgres_data: 
  